// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvt9hwWMS_Yx2dQ-CQH0MyPq_zEGpCHaY',
    appId: '1:1032249369427:web:33e41cc2b101a8a7e5f7a6',
    messagingSenderId: '1032249369427',
    projectId: 'hangman-7106b',
    authDomain: 'hangman-7106b.firebaseapp.com',
    storageBucket: 'hangman-7106b.appspot.com',
    measurementId: 'G-ETDSL7822S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvFSFJhAYGh5O-JXQaAu9Yj3m1Mez5svY',
    appId: '1:1032249369427:android:28c330414c0c3b49e5f7a6',
    messagingSenderId: '1032249369427',
    projectId: 'hangman-7106b',
    storageBucket: 'hangman-7106b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZS5ZnBCDfAmFUsneh3RQf9No58sCJsZU',
    appId: '1:1032249369427:ios:5d52100a7c93af93e5f7a6',
    messagingSenderId: '1032249369427',
    projectId: 'hangman-7106b',
    storageBucket: 'hangman-7106b.appspot.com',
    iosBundleId: 'com.example.hangMan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZS5ZnBCDfAmFUsneh3RQf9No58sCJsZU',
    appId: '1:1032249369427:ios:3df2ba9f978a79f9e5f7a6',
    messagingSenderId: '1032249369427',
    projectId: 'hangman-7106b',
    storageBucket: 'hangman-7106b.appspot.com',
    iosBundleId: 'com.example.hangMan.RunnerTests',
  );
}
